name: coghri_robai

services:
  eut_robai:
    container_name: "eut_robai"
    network_mode: host 
    ipc: host
    shm_size: 1gb
    runtime: ${DOCKER_RUNTIME:-runc}
    # user: "coghri"
    image: ${BUILT_IMAGE}
    privileged: true
    # user: "coghri"  # User will be created in the entrypoint script
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.xauth_docker/share/:/tmp/xauth/
      - ./.vscode:/workspace/.vscode
      - ../simple_py:/workspace/src/simple_py

    tty: true
    stdin_open: true
    environment:
      # - USER_ID=${USER_ID}
      # - GROUP_ID=${GROUP_ID}
      # - USERNAME=${USERNAME}
      - NVIDIA_VISIBLE_DEVICES=all 
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth   
      - AI_VENV=/opt/ros_python_env  
      # - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}  
      # - PULSE_SERVER=unix:/run/user/${USER_ID}/pulse/native
      # - PULSE_COOKIE=/home/coghri/.config/pulse/cookie
      # - ALSA_CARD=${ALSA_CARD}  # Set to the card number for your speaker
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    # cap_add:
    #   - NET_RAW
    #   - NET_ADMIN
    # security_opt:
    #   - seccomp:unconfined
    command: bash -c "source /workspace/install/setup.bash && /bin/bash"
    # entrypoint: ["/entrypoint.sh"]
