# EutRobAI Base Image: Jetson Thor / ARM64 ROS 2 Jazzy + PyTorch
#
# This Dockerfile is dedicated to Jetson ARM builds.
# It starts from an NVIDIA PyTorch image so CUDA and torch come from a
# Jetson-compatible base, then layers ROS 2 Jazzy on top.

ARG BASE_IMAGE="nvcr.io/nvidia/pytorch:25.08-py3-igpu"
FROM ${BASE_IMAGE} AS base

ARG BASE_IMAGE
ARG PYTHON_VERSION="3.12"
ARG PLATFORM_ARCH="arm"

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=jazzy
ENV ROS_WS=/ros2_ws
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    gosu \
    lcov \
    locales \
    lsb-release \
    nano \
    python3-dev \
    python3-pip \
    python3-pytest \
    python3-pytest-cov \
    python3-venv \
    software-properties-common \
    sudo \
    terminator \
    wget \
    build-essential \
    git \
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN python3 -m pip install --no-cache-dir rosdep

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo ${UBUNTU_CODENAME}) main" \
        > /etc/apt/sources.list.d/ros2.list

RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-vcstool \
    ros-${ROS_DISTRO}-desktop \
    ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
    ros-${ROS_DISTRO}-rmw-fastrtps-cpp \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/ros_python_env --system-site-packages \
    && /bin/bash -c "source /opt/ros_python_env/bin/activate && python -c 'import torch; print(torch.__version__); assert torch.version.cuda is not None'"

RUN mkdir -p /ros2_ws/src

WORKDIR /ros2_ws

RUN if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then \
      /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && rosdep init"; \
    else \
      echo "rosdep already initialized"; \
    fi

RUN apt-get update && \
    /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; \
      rosdep update; \
      rosdep install -y -r -q --from-paths src --ignore-src --rosdistro ${ROS_DISTRO};" \
    && rm -rf /var/lib/apt/lists/*

RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; colcon build --event-handlers console_direct+ --symlink-install;"

COPY ci_cd_coverage.sh /ci_cd_coverage.sh
RUN chmod +x /ci_cd_coverage.sh

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/bin/bash"]